# Generated by Django 3.0.6 on 2020-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_Num', models.CharField(blank=True, default='', max_length=10)),
                ('name_first', models.CharField(blank=True, default='', max_length=100)),
                ('name_last', models.CharField(blank=True, default='', max_length=100)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=100000)),
            ],
        ),
    ]
