# Generated by Django 3.0.6 on 2020-05-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_Num', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('name_first', models.CharField(blank=True, default='', max_length=100)),
                ('name_last', models.CharField(blank=True, default='', max_length=100)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=100000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.Account')),
            ],
        ),
    ]
