# Generated by Django 3.0.6 on 2020-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200526_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=10),
        ),
    ]
