# Generated by Django 3.0.6 on 2020-05-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200527_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
    ]
